import React,{useState,useEffect,useRef,useCallback} from 'react';
import {useAuth} from '../contexts/AuthContext';
import AuthForm from './AuthForm';
import {api,jsonRequest,errorMessage} from './api';
import {Portfolio,Purchase,PriceAlert,Feed,KARATS,CURRENCIES,validFeed,indicativePrice,totals,purchasePayload,localDate} from './model';
import './user.css';
type Page='home'|'prices'|'portfolio'|'purchases'|'alerts'|'account'|'help';
const pages:{id:Page;label:string;icon:string}[]=[{id:'home',label:'نظرة عامة',icon:'home'},{id:'prices',label:'أسعار الذهب',icon:'chart'},{id:'portfolio',label:'المحافظ',icon:'wallet'},{id:'purchases',label:'المشتريات',icon:'receipt'},{id:'alerts',label:'تنبيهات الأسعار',icon:'bell'},{id:'account',label:'الحساب',icon:'user'},{id:'help',label:'المساعدة',icon:'help'}];
function Icon({name}:{name:string}){
 const paths:Record<string,string>={home:'m3 10 9-7 9 7v10H3Z M9 20v-7h6v7',chart:'M4 4v16h16 M7 14l4-5 4 3 5-7',wallet:'M3 6h17v14H3Z M3 6V4h14 M15 11h6v5h-6Z',receipt:'M5 3h14v18l-3-2-4 2-4-2-3 2Z M8 8h8 M8 12h8',bell:'M5 16h14l-2-3V9a5 5 0 0 0-10 0v4Z M10 20h4',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0 M4 21v-2a8 8 0 0 1 16 0v2',help:'M12 17v1 M9 8a3 3 0 1 1 4 3c-1 .5-1 1-1 3 M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',menu:'M4 6h16 M4 12h16 M4 18h16',close:'m6 6 12 12 M6 18 18 6',refresh:'M20 8a9 9 0 1 0 1 8 M20 3v6h-6',plus:'M12 5v14 M5 12h14',logout:'M9 3H4v18h5 M9 12h12 m-4-4 4 4-4 4'};
 return <svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.home}/></svg>;
}
const number=(n:number)=>new Intl.NumberFormat('ar-SA',{maximumFractionDigits:2}).format(n);
const money=(n:number|null,c:string)=>n===null?'غير متاح':number(n)+' '+c;
const dateTime=(s:string)=>new Date(s).toLocaleString('ar-SA',{dateStyle:'medium',timeStyle:'short'});
function Empty({children}:{children:React.ReactNode}){return <div className="empty"><Icon name="wallet"/><p>{children}</p></div>;}
function CurrencySelect({value='SAR'}:{value?:string}){return <select name="currency" defaultValue={value}>{CURRENCIES.map(c=><option key={c}>{c}</option>)}</select>;}
function KaratSelect({value=24}:{value?:number}){return <select name="karat" defaultValue={value}>{KARATS.map(k=><option key={k} value={k}>عيار {k}</option>)}</select>;}
export default function UserWorkspace(){
 const {user,isLoading,logout}=useAuth();
 if(isLoading&&!user)return <div className="gold-web boot" dir="rtl" role="status">جارٍ التحقق من الجلسة…</div>;
 if(!user)return <AuthForm/>;
 return <Workspace key={String(user.id)} email={user.email} role={user.role} logout={logout}/>;
}
export function Workspace({email,role,logout}:{email:string;role:string;logout:()=>void}){
 const [page,setPage]=useState<Page>('home'),[menu,setMenu]=useState(false);
 const [portfolios,setPortfolios]=useState<Portfolio[]>([]),[purchases,setPurchases]=useState<Purchase[]>([]),[alerts,setAlerts]=useState<PriceAlert[]>([]);
 const [feed,setFeed]=useState<Feed|null>(null),[feedError,setFeedError]=useState(''),[priceCurrency,setPriceCurrency]=useState('SAR');
 const [loading,setLoading]=useState(true),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [dialog,setDialog]=useState<{type:'portfolio'|'purchase'|'alert';purchase?:Purchase}|null>(null),[confirm,setConfirm]=useState<{path:string;label:string}|null>(null),[formError,setFormError]=useState('');
 const [clock,setClock]=useState(Date.now());const active=useRef(true),loadSequence=useRef(0),writeLock=useRef(false),modalRef=useRef<HTMLDivElement>(null),headingRef=useRef<HTMLHeadingElement>(null);
 const loadData=useCallback(async()=>{
  const seq=++loadSequence.current;setLoading(true);setError('');
  try{
   const [ps,buys,first]=await Promise.all([api<Portfolio[]>('/portfolio'),api<Purchase[]>('/portfolio/purchase'),api<{items:PriceAlert[];total:number}>('/alerts?limit=100&page=1')]);
   if(!Array.isArray(ps)||!Array.isArray(buys)||!Array.isArray(first.items)||!Number.isFinite(first.total))throw new Error('Invalid response');
   const all=[...first.items];for(let p=2;all.length<first.total;p++){const next=await api<{items:PriceAlert[]}>('/alerts?limit=100&page='+p);if(!next.items.length)break;all.push(...next.items);}
   if(active.current&&seq===loadSequence.current){setPortfolios(ps);setPurchases(buys);setAlerts(all);setLoaded(true);}
  }catch(e){if(active.current&&seq===loadSequence.current)setError(errorMessage(e));}
  finally{if(active.current&&seq===loadSequence.current)setLoading(false);}
 },[]);
 const loadPrice=useCallback(async()=>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);
  try{const r=await fetch('https://raw.githubusercontent.com/ibr7h/gold-app-pwa/main/prices-live.json?t='+Date.now(),{cache:'no-store',signal:controller.signal});if(!r.ok)throw new Error();const d=validFeed(await r.json());if(active.current){setFeed(d);setFeedError('');}}
  catch{if(active.current)setFeedError('تعذر جلب تحديث السعر. تأكد من وقت آخر تحديث قبل استخدامه.');}finally{clearTimeout(timer);}
 },[]);
 useEffect(()=>{active.current=true;void loadData();void loadPrice();const timer=setInterval(()=>{setClock(Date.now());if(document.visibilityState==='visible')void loadPrice();},60000);
  const focus=()=>{if(document.visibilityState==='visible'){void loadData();void loadPrice();}};document.addEventListener('visibilitychange',focus);
  return()=>{active.current=false;loadSequence.current++;clearInterval(timer);document.removeEventListener('visibilitychange',focus);};},[loadData,loadPrice]);
 useEffect(()=>{const read=()=>{const id=location.hash.slice(1);if(pages.some(p=>p.id===id))setPage(id as Page);};read();window.addEventListener('hashchange',read);return()=>window.removeEventListener('hashchange',read);},[]);
 const navigate=(p:Page)=>{setPage(p);setMenu(false);location.hash=p;requestAnimationFrame(()=>headingRef.current?.focus());};
 useEffect(()=>{if(!message)return;const timer=setTimeout(()=>setMessage(''),6000);return()=>clearTimeout(timer);},[message]);
 useEffect(()=>{if(!dialog&&!confirm&&!menu)return;const previous=document.activeElement as HTMLElement,el=modalRef.current;
  const controls=()=>el?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),[tabindex="0"]');controls()?.[0]?.focus();
  const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!writeLock.current){setDialog(null);setConfirm(null);setMenu(false);}if(e.key==='Tab'&&el){const c=controls();if(!c?.length)return;if(e.shiftKey&&document.activeElement===c[0]){e.preventDefault();c[c.length-1].focus();}else if(!e.shiftKey&&document.activeElement===c[c.length-1]){e.preventDefault();c[0].focus();}}};
  document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previous?.focus();};},[dialog,confirm,menu]);
 const mutate=async(path:string,method:string,data?:object)=>{
  if(writeLock.current)return;writeLock.current=true;setBusy(true);setError('');setFormError('');setMessage('');
  try{await api(path,jsonRequest(method,data));if(!active.current)return;setDialog(null);setConfirm(null);setMessage('تم حفظ التغيير على الخادم.');await loadData();}
  catch(e){if(active.current){const msg=errorMessage(e);setFormError(msg);setError(msg);}}
  finally{writeLock.current=false;if(active.current)setBusy(false);}
 };
 const openDialog=(type:'portfolio'|'purchase'|'alert',purchase?:Purchase)=>{setFormError('');setDialog({type,purchase});};
 const submit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const data=new FormData(e.currentTarget);if(!dialog)return;
  try{
   if(dialog.type==='portfolio'){const name=String(data.get('name')||'').trim();if(!name)throw new Error('أدخل اسم المحفظة.');await mutate('/portfolio','POST',{name});}
   if(dialog.type==='purchase'){const payload=purchasePayload(data);await mutate(dialog.purchase?'/portfolio/purchase/'+dialog.purchase.id:'/portfolio/purchase',dialog.purchase?'PATCH':'POST',payload);}
   if(dialog.type==='alert'){const targetPrice=Number(data.get('targetPrice'));if(!Number.isFinite(targetPrice)||targetPrice<=0||targetPrice>=100000000)throw new Error('أدخل سعرًا موجبًا أقل من 100 مليون.');await mutate('/alerts','POST',{currency:String(data.get('currency')),karat:Number(data.get('karat')),targetPrice,direction:String(data.get('direction'))});}
  }catch(e){setFormError(e instanceof Error?e.message:'تحقق من القيم.');}
 };
 const stale=!feed||clock-Date.parse(feed.updatedAt)>30*60000||Date.parse(feed.updatedAt)>clock+5*60000;
 const summary=totals(purchases,feed),statusLabels={active:'نشط',paused:'متوقف',triggered:'تحقق الشرط'};
 const priceNote=<p className="fine">أسعار مرجعية مشتقة من سعر الأونصة، وليست عروض شراء أو بيع من متجر. التحويل SAR/USD يستخدم 3.75. المصنعية والضرائب غير مشمولة.</p>;
 const priceBlock=<section className="panel"><div className="section-heading"><div><p className="eyebrow">السعر المرجعي للجرام</p><h2>عيار 24 / {priceCurrency}</h2></div><label className="compact-label">العملة<select value={priceCurrency} onChange={e=>setPriceCurrency(e.target.value)}>{CURRENCIES.map(c=><option key={c}>{c}</option>)}</select></label></div>
 <div className="spot-price">{money(indicativePrice(feed,priceCurrency,24),priceCurrency)}</div><p className="price-time"><span className={'pill '+(stale||feedError?'warn':'good')}>{feedError?'تعذر التحديث':stale?'بيانات غير حديثة':'آخر سعر منشور'}</span>{feed?dateTime(feed.updatedAt):'لم يصل السعر بعد'}</p>
 {feedError&&<p className="notice warning">{feedError}</p>}<div className="karat-grid">{KARATS.slice(1).map(k=><div key={k}><span>عيار {k}</span><strong>{money(indicativePrice(feed,priceCurrency,k),priceCurrency)}</strong></div>)}</div>{priceNote}</section>;
 const nav=<><div className="nav-brand"><span className="brand-mark small">ذ</span><div><strong>ذهبي</strong><small>مساحتك الشخصية</small></div></div><nav aria-label="القائمة الرئيسية">{pages.map(p=><button key={p.id} className={'nav-item '+(p.id===page?'selected':'')} aria-current={p.id===page?'page':undefined} onClick={()=>navigate(p.id)}><Icon name={p.icon}/><span>{p.label}</span></button>)}</nav><div className="nav-account"><span className="avatar">{email[0].toUpperCase()}</span><span className="email" dir="ltr">{email}</span><button className="icon-button" title="تسجيل الخروج" aria-label="تسجيل الخروج" onClick={logout}><Icon name="logout"/></button></div></>;
 const content=()=>{
  if(page==='prices')return <>{priceBlock}<section className="panel"><h2>وضوح البيانات</h2><p>نُظهر وقت السعر الأصلي بدلًا من وقت فتح الصفحة. لا نعرض رسوم حركة أو نسب ارتفاع وانخفاض عند عدم توفر سجل موثوق لها.</p><p className="muted">المصدر: {feed?.source||'غير متاح'} · يتحدث العرض كل دقيقة أثناء فتح التطبيق.</p></section></>;
  if(page==='home')return <><div className="welcome"><div><p className="eyebrow">خطوة أقرب إلى متابعة أوضح</p><h2>كل ما يخص ذهبك، هنا.</h2><p>نظّم مقتنياتك وتابع قيمتها المرجعية بدون خلط العملات.</p></div><button className="primary" disabled={!loaded||busy} onClick={()=>openDialog(portfolios.length?'purchase':'portfolio')}><Icon name="plus"/>{portfolios.length?'تسجيل شراء':'إنشاء أول محفظة'}</button></div>
  <div className="overview-grid">{priceBlock}<section className="panel"><p className="eyebrow">حسابك بالأرقام</p><div className="count-grid"><div><strong>{loaded?portfolios.length:'—'}</strong><span>محافظ</span></div><div><strong>{loaded?purchases.length:'—'}</strong><span>مشتريات</span></div><div><strong>{loaded?alerts.filter(a=>a.status==='active').length:'—'}</strong><span>تنبيهات نشطة</span></div></div><div className="quick-actions">{pages.filter(p=>['portfolio','purchases','alerts'].includes(p.id)).map(p=><button key={p.id} onClick={()=>navigate(p.id)}><Icon name={p.icon}/>{p.label}<span>←</span></button>)}</div></section></div>
  <section className="panel"><h2>ملخص المقتنيات حسب العملة</h2>{!loaded?<p className="muted">لم يتم تحميل بيانات الحساب.</p>:!summary.length?<Empty>سجّل أول عملية شراء لعرض ملخص مقتنياتك.</Empty>:<div className="summary-grid">{summary.map(s=><div className="summary-card" key={s.currency}><span className="pill">{s.currency}</span><dl><dt>تكلفة الشراء</dt><dd>{money(s.cost,s.currency)}</dd><dt>الوزن الإجمالي</dt><dd>{number(s.weight)} جم</dd><dt>القيمة المرجعية {stale?'(سعر قديم)':''}</dt><dd>{money(s.value,s.currency)}</dd><dt>الفرق عن التكلفة</dt><dd className={s.value===null?'':s.value>=s.cost?'positive':'negative'}>{money(s.value===null?null:s.value-s.cost,s.currency)}</dd></dl></div>)}</div>}{priceNote}</section></>;
  if(page==='portfolio')return <section className="panel"><div className="section-heading"><div><h2>محافظك</h2><p className="muted">اجمع المشتريات حسب هدفك. تُحفظ البيانات في حسابك.</p></div><button className="primary" disabled={busy||!loaded} onClick={()=>openDialog('portfolio')}><Icon name="plus"/>محفظة جديدة</button></div>{!loaded?<Empty>لم يتم تحميل المحافظ بعد.</Empty>:!portfolios.length?<Empty>لا توجد محافظ بعد. أنشئ محفظتك الأولى.</Empty>:<div className="portfolio-grid">{portfolios.map(p=>{const rows=purchases.filter(b=>b.portfolioId===p.id);return <article className="portfolio-card" key={p.id}><span className="card-icon"><Icon name="wallet"/></span><h3>{p.name}</h3><p className="muted">{rows.length} سجلات شراء</p>{totals(rows,feed).map(s=><p key={s.currency}>تكلفة {s.currency}: <strong>{money(s.cost,s.currency)}</strong></p>)}<button className="danger text-button" disabled={busy||rows.length>0} onClick={()=>{setFormError('');setConfirm({path:'/portfolio/'+p.id,label:p.name});}}>حذف المحفظة الفارغة</button></article>;})}</div>}</section>;
  if(page==='purchases')return <section className="panel"><div className="section-heading"><div><h2>سجل المشتريات</h2><p className="muted">الوزن بالجرام والسعر لكل جرام. هذه سجلات مقتنياتك، وليست أوامر تداول.</p></div><button className="primary" disabled={busy||!loaded} onClick={()=>openDialog(portfolios.length?'purchase':'portfolio')}><Icon name="plus"/>{portfolios.length?'تسجيل شراء':'إنشاء محفظة أولًا'}</button></div>{!loaded?<Empty>لم يتم تحميل المشتريات بعد.</Empty>:!purchases.length?<Empty>لا توجد مشتريات مسجلة.</Empty>:<div className="records">{purchases.map(p=><article className="record" key={p.id}><div className="record-title"><span className="card-icon"><Icon name="receipt"/></span><div><h3>ذهب عيار {p.karat}</h3><p className="muted">{portfolios.find(x=>x.id===p.portfolioId)?.name||'محفظة'} · {p.purchasedAt.slice(0,10)}</p></div><strong className="record-total">{money(Number(p.totalPrice),p.currency)}</strong></div><dl className="record-details"><div><dt>الوزن</dt><dd>{number(Number(p.weightGrams))} جم</dd></div><div><dt>سعر الجرام</dt><dd>{money(Number(p.unitPrice),p.currency)}</dd></div><div className="actions"><button className="secondary" disabled={busy} onClick={()=>openDialog('purchase',p)}>تعديل</button><button className="danger text-button" disabled={busy} onClick={()=>{setFormError('');setConfirm({path:'/portfolio/purchase/'+p.id,label:'سجل الشراء'});}}>حذف</button></div></dl></article>)}</div>}</section>;
  if(page==='alerts')return <section className="panel"><div className="section-heading"><div><h2>تنبيهات الأسعار</h2><p className="muted">راقب بلوغ سعر شراء الجرام المحفوظ في الخادم حدًا تحدده.</p></div><button className="primary" disabled={busy||!loaded} onClick={()=>openDialog('alert')}><Icon name="plus"/>تنبيه جديد</button></div><p className="notice info">يُفحص الشرط على الخادم بحسب بياناته وجدول تحديثه، وقد تختلف عن السعر المرجعي المعروض هنا. لا يعني حفظ التنبيه تفعيل إشعار Push عند إغلاق التطبيق. استخدم «تحديث» للتحقق من الحالة.</p>{!loaded?<Empty>لم يتم تحميل التنبيهات بعد.</Empty>:!alerts.length?<Empty>لا توجد تنبيهات. أضف السعر الذي تريد متابعته.</Empty>:<div className="portfolio-grid">{alerts.map(a=><article className="portfolio-card" key={a.id}><div className="section-heading"><span className="card-icon"><Icon name="bell"/></span><span className={'pill '+(a.status==='active'?'good':a.status==='triggered'?'warn':'')}>{statusLabels[a.status]}</span></div><h3>عيار {a.karat} · {a.currency}</h3><p>{a.direction==='above'?'عند وصول السعر إلى أو أعلى من':'عند وصول السعر إلى أو أقل من'}</p><strong className="alert-price">{money(Number(a.targetPrice),a.currency)}</strong><p className="fine">آخر تغيير: {dateTime(a.updatedAt)}</p><div className="actions"><button className="secondary" disabled={busy} onClick={()=>void mutate('/alerts/'+a.id+(a.status==='active'?'/pause':'/activate'),'POST')}>{a.status==='active'?'إيقاف مؤقت':a.status==='triggered'?'إعادة التفعيل':'تفعيل'}</button><button className="danger text-button" disabled={busy} onClick={()=>{setFormError('');setConfirm({path:'/alerts/'+a.id,label:'التنبيه'});}}>حذف</button></div></article>)}</div>}</section>;
  if(page==='account')return <section className="panel"><span className="avatar large">{email[0].toUpperCase()}</span><h2>حساب المستخدم</h2><p dir="ltr">{email}</p><p className="muted">صلاحية الحساب: {role==='admin'?'مدير':role==='trader'?'تاجر':'مستخدم'} · الواجهة الحالية: المستخدم</p><p>تُحمّل المحافظ والمشتريات والتنبيهات من حسابك بعد التحقق من الجلسة. يُجدَّد رمز الدخول تلقائيًا ما دامت جلسة التجديد صالحة.</p><p className="notice info">تغيير الاسم وكلمة المرور واستعادة كلمة المرور غير متاحة من واجهة الخادم الحالية.</p><button className="secondary" onClick={logout}><Icon name="logout"/>تسجيل الخروج من هذا المتصفح</button></section>;
  return <section className="panel help-panel"><h2>دليل سريع</h2>{[['كيف أبدأ؟','أنشئ محفظة، ثم سجّل عيار الذهب ووزنه بالجرام وسعر الشراء لكل جرام. يحسب التطبيق الإجمالي تلقائيًا.'],['هل البيانات تجريبية؟','المحافظ والمشتريات والتنبيهات المعروضة هي بيانات حسابك من الخادم. الحساب الجديد يبدأ فارغًا.'],['كيف تُحسب القيمة؟','سعر الجرام مشتق من سعر الأونصة ونقاء العيار. تُعرض العملات منفصلة، دون مصنعية أو ضرائب أو هامش بيع افتراضي.'],['هل التنبيهات تعمل والتطبيق مغلق؟','الخادم يحفظ الشرط وحالته. إرسال إشعارات إلى الجهاز عند إغلاق التطبيق لم يُفعّل في نسخة الويب الحالية.'],['أين العروض والتجار والرسوم البيانية؟','المحتوى السابق لهذه الأقسام كان تجريبيًا. لن يُعرض كبيانات فعلية حتى تُربط الأقسام بمصادرها الحقيقية.'],['كيف أثبت التطبيق؟','على iPhone افتحه في Safari ثم مشاركة ← إضافة إلى الشاشة الرئيسية. في المتصفحات الداعمة استخدم خيار تثبيت التطبيق.']].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>;
 };
 return <div className="gold-web workspace" dir="rtl" lang="ar"><aside className="desktop-nav">{nav}</aside><div className="workspace-main"><header className="topbar"><button className="icon-button menu-trigger" aria-label="فتح القائمة" aria-expanded={menu} onClick={()=>setMenu(true)}><Icon name="menu"/></button><div><p className="eyebrow">ذهبي / حساب المستخدم</p><h1 tabIndex={-1} ref={headingRef}>{pages.find(p=>p.id===page)?.label}</h1></div><button className="secondary refresh-button" disabled={loading||busy} onClick={()=>{void loadData();void loadPrice();}}><Icon name="refresh"/><span>{loading?'جارٍ التحميل…':'تحديث'}</span></button></header><main className="workspace-content" aria-busy={loading}>{error&&<div className="notice error" role="alert">{error} <button className="text-button" disabled={loading} onClick={()=>void loadData()}>إعادة المحاولة</button></div>}{message&&<p className="notice success" role="status">{message}</p>}{loading&&!loaded&&<p className="notice info" role="status">جارٍ تحميل بيانات حسابك…</p>}{content()}<footer>© 2026 Ibrahim Alneami — All Rights Reserved · User Web 1.1</footer></main></div>
 {menu&&<div className="mobile-nav-backdrop" onClick={()=>setMenu(false)}><div className="mobile-nav" ref={modalRef} role="dialog" aria-modal="true" aria-label="قائمة التنقل" onClick={e=>e.stopPropagation()}><button className="icon-button close-menu" aria-label="إغلاق القائمة" onClick={()=>setMenu(false)}><Icon name="close"/></button>{nav}</div></div>}
 {(dialog||confirm)&&<div className="dialog-backdrop"><div className="dialog" ref={modalRef} role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div className="section-heading"><h2 id="dialog-title">{confirm?'تأكيد الحذف':dialog?.type==='portfolio'?'محفظة جديدة':dialog?.type==='alert'?'تنبيه جديد':dialog?.purchase?'تعديل سجل الشراء':'تسجيل شراء'}</h2><button className="icon-button" aria-label="إغلاق" disabled={busy} onClick={()=>{setDialog(null);setConfirm(null);}}><Icon name="close"/></button></div>
 {confirm?<><p>هل تريد حذف {confirm.label}؟ لا يمكن التراجع عن الحذف من التطبيق.</p><div className="actions"><button className="secondary" disabled={busy} onClick={()=>setConfirm(null)}>إلغاء</button><button className="danger-button" disabled={busy} onClick={()=>void mutate(confirm.path,'DELETE')}>{busy?'جارٍ الحذف…':'حذف'}</button></div></>:<form onSubmit={submit}>
 {dialog?.type==='portfolio'&&<label>اسم المحفظة<input name="name" required maxLength={80} placeholder="مثال: ادخار الأسرة"/></label>}
 {dialog?.type==='purchase'&&<><label>المحفظة<select name="portfolioId" defaultValue={dialog.purchase?.portfolioId||portfolios[0]?.id} required>{portfolios.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="form-grid"><label>العيار<KaratSelect value={dialog.purchase?.karat}/></label><label>العملة<CurrencySelect value={dialog.purchase?.currency}/></label><label>الوزن بالجرام<input name="weightGrams" type="number" inputMode="decimal" min="0.0001" max="99999999" step="0.0001" required defaultValue={dialog.purchase?.weightGrams}/></label><label>سعر الجرام عند الشراء<input name="unitPrice" type="number" inputMode="decimal" min="0.0001" max="99999999" step="0.0001" required defaultValue={dialog.purchase?.unitPrice}/></label></div><label>تاريخ الشراء<input name="purchasedAt" type="date" required max={localDate()} defaultValue={dialog.purchase?.purchasedAt.slice(0,10)||localDate()}/></label><p className="fine">الإجمالي = الوزن بالجرام × سعر الجرام. أدخل بيانات الشراء الفعلية.</p></>}
 {dialog?.type==='alert'&&<><div className="form-grid"><label>العيار<KaratSelect/></label><label>العملة<CurrencySelect/></label></div><label>السعر المستهدف لكل جرام<input name="targetPrice" type="number" inputMode="decimal" min="0.0001" max="99999999" step="0.0001" required/></label><label>الشرط<select name="direction"><option value="above">السعر يساوي أو يتجاوز الهدف</option><option value="below">السعر يساوي أو يقل عن الهدف</option></select></label></>}
 {formError&&<p className="notice error" role="alert">{formError}</p>}<div className="actions"><button className="primary" disabled={busy}>{busy?'جارٍ الحفظ…':'حفظ'}</button><button type="button" className="secondary" disabled={busy} onClick={()=>setDialog(null)}>إلغاء</button></div></form>}{confirm&&formError&&<p className="notice error" role="alert">{formError}</p>}
 </div></div>}</div>;
}
